### ISSUE TITLE
Link for release 1.0.0 zip is broken

### ISSUE THREAD

**Issue by alfredodev** [jmalarcon/MIIS#1]
In:
https://github.com/jmalarcon/MIIS/releases
The link for the 1.0.0 zip is broken:
https://github.com/jmalarcon/MIIS/releases/download/1.0.0/MIIS-1.0.0.zip

**Comment by jmalarcon** [comment]
Yes, please use the 1.0.1 link, wich is the "good2 version to download. Thanks.
