### ISSUE TITLE
Questions about MIIS

### ISSUE THREAD

**Issue by wstaelens** [jmalarcon/MIIS#11]
Several questions that are not clear from the documentation.

1. Is there a possibility to add search to the site? if yes? how 

1. When using subdirectories, is it possible to link to pages without having the .md file name?

```
Site/SubFolder/index.md
Site/SubFolder/otherpage.md
```
now if I use toc.md I link to:
` [Some link](/SubFolder/otherpage.md)`
but the url contains .md like: http://mysite.com/SubFolder/otherpage.md 
Is there a way to remove the .md from the url? if I do:
`[Some link](/SubFolder/otherpage)`  I get an error not found.

**Comment by jmalarcon** [comment]
Hi:

1.- No, there's no currently support for search
2.- The only way to get rid of the .md extension is by configuring an IIS rewrite for that kind of path so it would call the correct file under the hood but show the  file without an extension in the browser's url. This is standard IIS stuff.

**Comment by wstaelens** [comment]
@jmalarcon any chance to add search similar to https://github.com/madskristensen/MarkSite ?

(I'm writing an editor for MIIS in WPF so that I can easily publish site and add new pages.)

**Comment by jmalarcon** [comment]
Hi:

I didn't know that project. I've been taking a quick look at it and I'm not able to identify any search feature or facility.

MIIS is a "cross" between a Static Site Generator (SSG)  and a CMS. In a SSG adding search is pretty straight-forward because you can generate the index while compiling it to static files. In a CMS it's even easier because you have a database to keep all your information. In this "Cross" it's more difficult because you'll need to build an index out-of-band (under demand or periodically).

I have in mind to use [Lunr.js](https://lunrjs.com) to enable search on any site, and I'd like to develop an index builder for Lunr so it will be easy to index any site and update the indexes on demand. That would enable adding searches to any MIIS site easily on the client-side. However, right now it's only an idea in my to-do list, and I don't have a lot of time unfortunately 😞 

If I ever develop that I'll let you know.

I'd love to take a look at your MIIS Editor once it's available. Thanks!

**Comment by wstaelens** [comment]
@jmalarcon still very very very early screenshot.
Will be easier for me and colleagues to write and manage MIIS sites via such editor. I've now added basic markdown syntax highlighting, i can add/remove folders, markdown files. 
Still a lot of work to do 😅 
![winking miiseditv0a](https://user-images.githubusercontent.com/7447285/42219112-fffc8072-7eca-11e8-9b98-1dd1486930a8.png)

**Comment by jmalarcon** [comment]
Looks great.

I have several sites up and running with MIIS. I usually work directly on my computer with VSCode and Git and deploy the sites just using Git. At the end is as simple as to write text documents.

Thanks!

**Comment by jmalarcon** [comment]
I don't know. I'm really busy right now and making this will take a lot of time, so I don't have a timeline for it, and neither for other ideas I have in the pipeline :-S

Sorry.

**Comment by wstaelens** [comment]
or can you give instructions, maybe I can have a look at it. 
would it be just loading all markdown pages, adding title and the markdown content as content for lunr and keeping it all in memory?

**Comment by jmalarcon** [comment]
In fact what I'm planning is a generic search service, not only for MIIS, so I need to write a crawler that takes into account a lot of things. Normally you would use MIIS with other systems at the same time (such as e-commerce products or similar) so simply indexing the .md files is not enough. However Lunr is very easy to use and build your own index for the .md files, directly in disk, would be easier. You'll keep the .json file in disk with the JSON needed for Lunr to work.

**Comment by wstaelens** [comment]
> 2.- The only way to get rid of the .md extension is by configuring an IIS rewrite for that kind of path so it would call the correct file under the hood but show the file without an extension in the browser's url. This is standard IIS stuff.

```XML
  <system.webServer>
<rewrite><rules>
	<rule name="rewritemd">
           <match url="(.*)" />
           <conditions logicalGrouping="MatchAll">
             <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
             <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
           </conditions>
           <action type="Rewrite" url="{R:1}.md" />
         </rule> 
</rules></rewrite>
</system.webServer>
```

I'm stuck with this rewrite rule, I need to remove all .md extensions to get it working. 
would prefer if I still could use ```[some link](/foo/bar.md)``` but don't show bar.md but only bar (by still using bar.md url). 

Never written any IIS rewrite rule before.

**Comment by jmalarcon** [comment]
Hi:

You'll need 3 rules to make it work:

```
<rule name="RemoveTrailingSlashRule" stopProcessing="true">
    <match url="(.*)/$" />
    <conditions>
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
        <add input="{URL}" pattern=".*/[^.]*\.[\d\w]+$" negate="true" />
    </conditions>
    <action type="Redirect" url="{R:1}" />
</rule>
<rule name=".md files without extension" stopProcessing="true">
    <match url="^(.*)$" />
    <conditions logicalGrouping="MatchAll">
        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" /> 
        <add input="{REQUEST_FILENAME}.md" matchType="IsFile" />
    </conditions>
    <action type="Rewrite" url="{R:0}.md" />
</rule>
<rule name=".mdh files without extension" stopProcessing="true">
    <match url="^(.*)$" />
    <conditions logicalGrouping="MatchAll">
        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" /> 
        <add input="{REQUEST_FILENAME}.mdh" matchType="IsFile" />
    </conditions>
    <action type="Rewrite" url="{R:0}.mdh" />
</rule>
```

The `RemoveTrailingSlashRule` is needed because if you get rid of the extension, it shouldn't be mistaken with a folder. The other two rules are self explanatory.

HTH

**Comment by wstaelens** [comment]
thanks. Now i need to update all my links without .md otherwise it always links and shows .md in the url.

**Comment by wstaelens** [comment]
@jmalarcon I've been busy 😄 👍 

![miisedit 4](https://user-images.githubusercontent.com/7447285/43885540-7745e046-9bb9-11e8-94d3-27338b3ed706.png)
