### ISSUE TITLE
Menu issues

### ISSUE THREAD

**Issue by wstaelens** [jmalarcon/MIIS#15]
1) How do i make sure only the first level is visible in the menu (Antwerpen, Limburg, …) 
and only the children becoming visible after clicking on a parent:
example:
www .archief.be

There seems also be an issue in application.cs:

> SCRIPT5007: SCRIPT5007: Unable to get property 'addEventListener' of undefined or null reference

but in the source file itself I can't see it, it is compacted/minimized javascript.

**Comment by jmalarcon** [comment]
Hi:

I inherited the minified file from the original template, from MKDocs, so I don't have the original one either. 

However, if you "prettyfie" the file using the small button you have on Chrome Devtols, you can see what's launching the exception: it's the missing search box in the MIIS template that the original MKDocs one had, although I hope to add it sometime in the future:

Here you have a full explanation I recorded for you: https://cl.ly/t3kd

HTH
