### ISSUE TITLE
Using the $&, $$ and some other $ combinations in content leads to disappearing

### ISSUE THREAD

**Issue by jmalarcon** [jmalarcon/MIIS#28]
As you can see in the screenshots for the  `$'`  issue a new parapraph is opened and the `$'` is not rendered in the html at all.

When I had a look on [babelmark ](https://babelmark.github.io/?text=%23%23+Codeblock+with+%24%E2%80%9C%0A%60%60%60%0A+++%24%22%0A%60%60%60%0A%60%24%22%60%0A%23%23+Usage+of+%24+and+%27+as+following+characters%0AAfter+the+occurrence+of+the+2+characters+%60%24%27%60+%0Athe+additional+text+that+will+appear+at+the+bottom+of+the+page+outside+of+the+main+template.%0A
)
the Markdig implementation renders it correctly. Sure that the issue does not exist in the MIIS logic?

![AdditionalTextAppearsAtTheBottom](https://user-images.githubusercontent.com/14054526/54900418-7638a300-4ed3-11e9-9db8-41fe24403720.png)
![babelmark3 _ Compare Markdown Implementations](https://user-images.githubusercontent.com/14054526/54900420-79339380-4ed3-11e9-8d65-77af1fe02fef.png)

Thank you very much!

_Originally posted by @ritti in https://github.com/jmalarcon/MIIS/issues/27#issuecomment-476076977_

**Comment by jmalarcon** [comment]
Fixed in commit [60d729c670f9c1359c19e1247d7164762395d71b](https://github.com/jmalarcon/MIIS/commit/60d729c670f9c1359c19e1247d7164762395d71b).

Although the most common case of using substitution expressions such as $0, $1... in the content was covered, there were other [substitution expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#substitutions) in RegExp that I missed. Now it's fixed in a more wide and expeditive way.

Thanks to @ritti for pointing out this.

**Comment by ritti** [comment]
Hi again,
unfortunately there seems to be one issue left with `$`.
Markdown content:
``` $someText$ ```
Output on MIIS (plain HTML from Markdown)
``` \(someText\)```
Maybe you can have a look into it.
Thanks

**Comment by jmalarcon** [comment]
😞 I'll try to take a look, but since I'm planning to change the rendering process to make it compatible with Liquid, maybe it's better to wait for that change altogether. I plan to devote some time to it very soon.
