### ISSUE TITLE
Resolved - IIS Install

### ISSUE THREAD

**Issue by smasterson** [jmalarcon/MIIS#31]
I wanted to leave a note for anyone else that may have struggled with an IIS install.

To install on a vanilla Windows Server 2016/2019:

- Install IIS and ASP.NET4.5

```
Install-WindowsFeature Web-Server,Web-Asp-Net45 -IncludeManagementTools
```

- **Install** [URL Rewrite](https://www.iis.net/downloads/microsoft/url-rewrite)

- Copy contents of `MIIS-v3.4.0.-Release` to C:\inetpub\wwwroot

Wolla :tada:

**Comment by jmalarcon** [comment]
Hi Shawn:

Thanks for the tip!

ASP.NET 4.5+ is one of the requirements in the documentation [here](https://miis.azurewebsites.net/], but I didn't notice that "URL Rewrite" needed to be installed on its own, because my templates for Windows Server always have it included.
