### ISSUE TITLE
Help wanted: readthedocs subsections 

### ISSUE THREAD

**Issue by k1ngf15h3r** [jmalarcon/MIIS#5]
My goal is to make a section maybe called "Nextcloud" and subsections for clients and administrators. But when I use ` [Nextcloud](nextcloud/index.md) ` a navigation link I got navigation errors when I click the link when I am already inside the section.

**Comment by jmalarcon** [comment]
Hi:

Use a toc.md file inside the subfolder, and the links would be correct. You can change the name of the toc.md file in the web.config.

Another option is just to use absolute paths (begining with /), but the first option is better.

Tell me if this works for you.

Cheers!

**Comment by k1ngf15h3r** [comment]
hi,

tried it with the `toc.md` inside the subfolder but this doesn't work. Does not matter if I write `nextcloud/index.md` or `index.md` in the second toc.md file. everytime I am on the Nextcloud Index page the navigation link will be like `http://www.example.com/nextcloud/nextcloud/index.md` 

the second solutions seems to be easier to maintenain because you only have to manage one `toc.md` file and it is working with the leading `/` 👍

**Comment by jmalarcon** [comment]
If you use the ToC inside the folder you don't need to use the name of the folder in the links. This secondary files are used to define a different ToC in each folder if needed or, if missing, use the main one in the root.
