### ISSUE TITLE
No linking md files without extension

### ISSUE THREAD

**Issue by tmfo** [jmalarcon/MIIS#7]
Hi
I downloaded your latest Release, but the Tool does not support links without Extension. Example (100E75FF). It works (100E75FF.md). But our documentation tool result do generate files otherwise.

The VisualStudio Plugin (MarkdownEditor) using the same Core (markdig) and its supports this Linking.
And that's why I using your Viewer.

**Comment by jmalarcon** [comment]
I don't get your issue (maybe I'm not understanding your English very well). What do you mean by "doesn't support links without extension"?

If you add any link to your markdown, with or without a file extension, they get correctly converted and linked in the resulting HTML. In the new version I'm about to launch you can use `~/` to point to the root folder of the web application, even if it's a virtual folder, and they would work OK too.

Please, link a file with a sample or copy and paste code to know exactly what you mean.

**Comment by wstaelens** [comment]
The problem he has is the same question I had.

If you add a markdown link to /foo you get a not found html page in IIS. however if you add a markdown link to /foo.md the html page is found. 


 I guess it would be good to add some documentation about how to configure IIS to make sure /foo.md and /foo (without .md) also works.
